name: Build code
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.yaml'
      - '*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: |
        npm install
        npm install @angular/cli
    - name: Build
      run: ng build
